name: primeira-pipeline
on:
  push:
    branches: ["main", "develop"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro pipeline"
          echo "Parabéns !!!"
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: ['primeiro-job']
    steps:
      - name: "Verificação da versão do NodeJS atual antes de instalar a nova"
        run: node --version
      - name: "Definição da versão 20.13.1 do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
      - name: "Verificação da versão do NodeJS atual depois da instalação"
        run: node --version
