name: primeira-pipeline
on:
  push:
    branches: ["main", "develop"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro pipeline"
          echo "Parabéns !!!"
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
